apiVersion: v1
kind: Service
metadata:
  name: helloboot
  labels:
    app: helloboot
    service: helloboot
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: helloboot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloboot-v1
  labels:
    app: helloboot
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloboot
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
      labels:
        app: helloboot
        version: v1
    spec:
      containers:
      - name: helloboot
        image: my-cluster-registry:5000/test-metrics:0.0.2
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080
